In [1]:
# Q1 (a)
import numpy as np
arr = np.array([1,2,3,6,4,5])
reversed_array = arr[::-1]
print(reversed_array)

[5 4 6 3 2 1]


In [2]:
#(b) Method 1
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()
print(flat1)


[1 2 3 2 4 5 1 2 3]


In [3]:
# Method 2
flat2 = array1.ravel()
print(flat2)


[1 2 3 2 4 5 1 2 3]


In [4]:
#(c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
#Method 1
print(np.array_equal(arr1,arr2))
#Method 2
print(arr1==arr2)

True
[[ True  True]
 [ True  True]]


In [6]:
#(d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
values,counts = np.unique(x,return_counts = True)
most_freq = values[np.argmax(counts)]
print("Most freq in x : ", most_freq)

indices = np.where(x == most_freq)[0]
print(indices)

Most freq in x :  1
[0 5 7 8 9]


In [7]:
#(e)
gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
#(i)
total_sum = gfg.sum()
print(total_sum)

45


In [8]:
#(ii)
row_sum = gfg.sum(axis = 1)
print(row_sum)

[[14]
 [16]
 [15]]


In [9]:
#(iii)
col_sum = gfg.sum(axis=0)
print(col_sum)

[[20  9 16]]


In [10]:
#(f)
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
#(i)
diagonal = np.trace(n_array)
print(diagonal)

176


In [11]:
#(ii)
eigen_values = np.linalg.eig(n_array)
print(eigen_values)

(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))


In [12]:
#(iii)
eigenvec = np.linalg.eig(n_array)
print(eigenvec)

(array([98.16835147, 28.097044  , 49.73460452]), array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))


In [13]:
#(iv)
inverse = np.linalg.inv(n_array)
print(inverse)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [14]:
#(v)
determinant = np.linalg.det(n_array)
print(determinant)

137180.0000000001


In [15]:
#(g) (i)
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
product = np.dot(p,q)
print(product)

cov_matrix = np.cov(p.flatten(),q.flatten())
print(cov_matrix)

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]


In [16]:
#(ii)
p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
pro2 = np.dot(p,q)
print(pro2)

cov_mat = np.cov(p.flatten(),q.flatten())
print(cov_mat)

[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [17]:
#(h) (i)
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
inner = np.inner(x,y)
print(inner)

#(ii)
outer = np.outer(x,y)
print(outer)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [18]:
#(iii)
from itertools import product
cartesian = np.array([np.concatenate([i,j]) for i,j in product(x,y)])
print(cartesian)

[[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


In [19]:
#Q2
#(a)
array = np.array([[1,-2,3],[-4,5,-6]])
abs_array = np.abs(array)
print(abs_array)

[[1 2 3]
 [4 5 6]]


In [20]:
#(ii)
percentile_flat = [np.percentile(array,p) for p in [25,50,75]]
print(percentile_flat)

#per column
percentile_cols = {f"{p}th" : np.percentile(array,p,axis=0) for p in [25,50,75]}
print(percentile_cols)

#per row
percentile_rows = {f"{p}th" : np.percentile(array,p,axis=1) for p in [25,50,75]}
print(percentile_rows)

[-3.5, -0.5, 2.5]
{'25th': array([-2.75, -0.25, -3.75]), '50th': array([-1.5,  1.5, -1.5]), '75th': array([-0.25,  3.25,  0.75])}
{'25th': array([-0.5, -5. ]), '50th': array([ 1., -4.]), '75th': array([2. , 0.5])}


In [21]:
#(iii)
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)
print(f"Flattened mean: {mean_flat}, median: {median_flat}, std: {std_flat}")


Flattened mean: -0.5, median: -0.5, std: 3.8622100754188224


In [22]:
# for column 
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print(f"Column-wise mean: {mean_col}")
print(f"Column-wise median: {median_col}")
print(f"Column-wise std: {std_col}")


Column-wise mean: [-1.5  1.5 -1.5]
Column-wise median: [-1.5  1.5 -1.5]
Column-wise std: [2.5 3.5 4.5]


In [23]:
# for row
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print(f"Row-wise mean: {mean_row}")
print(f"Row-wise median: {median_row}")
print(f"Row-wise std: {std_row}")


Row-wise mean: [ 0.66666667 -1.66666667]
Row-wise median: [ 1. -4.]
Row-wise std: [2.05480467 4.78423336]


In [25]:
#Q2 (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
 #(i)
floor_values = np.floor(a)
print("Floor values:", floor_values)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]


In [26]:
#(ii)
ceil_vals = np.ceil(a)
print(ceil_vals)

[-1. -1. -0.  1.  2.  2.  3.]


In [27]:
#(iii)
trunc_values = np.trunc(a)
print("Truncated values:", trunc_values)


Truncated values: [-1. -1. -0.  0.  1.  1.  3.]


In [28]:
#(iv)
round_values = np.round(a)
print("Rounded values:", round_values)


Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [29]:
# Q3 (a)
# (i) 
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

#(ii)
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

#(iii)
four_smallest = np.partition(array, 4)[:4]
print("4 smallest elements:", four_smallest)

#(iv)
five_largest = np.partition(array, -5)[-5:]
print("5 largest elements:", five_largest)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [16 10 16 52]
5 largest elements: [ 16  52  62  54 453]


In [30]:
#(b) (i)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_elements = array[array % 1 == 0]
print("Integer elements only:", integer_elements)

#(ii)
float_elements = array[array % 1 != 0]
print("Float elements only:", float_elements)



Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [34]:
#Q4
from PIL import Image
import numpy as np

def img_to_array(path):
    # Load image using PIL
    img = Image.open(path)
    
    # Convert image to numpy array
    arr = np.array(img)
    
    # Check if image is grayscale or RGB
    if len(arr.shape) == 2:
        # Grayscale image
        filename = "grayscale_image.txt"
    elif len(arr.shape) == 3 and arr.shape[2] == 3:
        # RGB image
        filename = "rgb_image.txt"
    else:
        raise ValueError("Unsupported image format or channels")
    
    # Save numpy array to text file
    # Using np.savetxt for 2D array (grayscale)
    # For RGB (3D), save each channel separately or reshape accordingly
    if len(arr.shape) == 2:
        np.savetxt(filename, arr, fmt='%d')
    else:
        # Reshape 3D array to 2D for saving
        reshaped_arr = arr.reshape(-1, arr.shape[2])
        np.savetxt(filename, reshaped_arr, fmt='%d')
    
    print(f"Image saved as text file: {filename}")

#(b)
def load_image_array(filename, shape=None):
    data = np.loadtxt(filename, dtype=int)
    if shape:
        data = data.reshape(shape)
    return data

